import 'package:flutter/material.dart';
import 'core/constants/colors.dart';

ThemeData lightTheme = ThemeData(
  brightness: Brightness.light,
  colorScheme: ColorScheme(
    brightness: Brightness.light,
    primary: AppColors.kPrimaryColor,
    onPrimary: AppColors.kWhiteColor,
    primaryContainer: AppColors.kSecondColor,
    onPrimaryContainer: AppColors.kBlackColor,
    secondary: AppColors.kSecondColor,
    onSecondary: AppColors.kPrimaryColor,
    secondaryContainer: AppColors.kThirtColor,
    onSecondaryContainer: AppColors.kBlackColor,
    tertiary: AppColors.kThirtColor,
    onTertiary: AppColors.kPrimaryColor,
    error: AppColors.kRedColor,
    onError: AppColors.kWhiteColor,
    errorContainer: AppColors.kRedColor.withOpacity(0.1),
    onErrorContainer: AppColors.kRedColor,
    surface: AppColors.kWhiteColor,
    onSurface: AppColors.kBlackColor,
    surfaceVariant: AppColors.kGreyColor.withOpacity(0.1),
    outline: AppColors.kGreyColor,
    background: AppColors.kWhiteColor,
    onBackground: AppColors.kBlackColor,
    shadow: Colors.black.withOpacity(0.2),
    inverseSurface: AppColors.kBlackColor,
    onInverseSurface: AppColors.kWhiteColor,
    inversePrimary: AppColors.kPrimaryColor,
    surfaceTint: AppColors.kPrimaryColor,
    scrim: Colors.black.withOpacity(0.5),
  ),
  scaffoldBackgroundColor: AppColors.kWhiteColor,
  cardColor: AppColors.kWhiteColor,
  dialogBackgroundColor: AppColors.kWhiteColor,
  iconTheme: const IconThemeData(color: AppColors.kPrimaryColor),
  textTheme: const TextTheme(
    titleLarge: TextStyle(
      fontSize: 25,
      fontWeight: FontWeight.w700,
      fontFamily: "Cairo-Bold",
      color: Colors.black,
    ),
    bodyMedium: TextStyle(
      fontSize: 15,
      fontWeight: FontWeight.w400,
      fontFamily: "Cairo-Bold",
      color: Colors.black,
    ),
    bodySmall: TextStyle(fontSize: 15, color: Colors.grey),
  ),
);

ThemeData darkTheme = ThemeData(
  brightness: Brightness.dark,
  colorScheme: ColorScheme(
    brightness: Brightness.dark,
    primary: AppColors.kPrimaryColorDarkMode,
    onPrimary: AppColors.kWhiteColor,
    primaryContainer: AppColors.kThirtColorDarkMode,
    onPrimaryContainer: AppColors.kWhiteColor,
    secondary: AppColors.kSecondColorDarkMode,
    onSecondary: AppColors.kWhiteColor,
    secondaryContainer: AppColors.kThirtColorDarkMode,
    onSecondaryContainer: AppColors.kWhiteColor,
    tertiary: AppColors.kThirtColorDarkMode,
    onTertiary: AppColors.kWhiteColor,
    error: AppColors.kRedColor,
    onError: AppColors.kWhiteColor,
    errorContainer: AppColors.kRedColor.withOpacity(0.2),
    onErrorContainer: AppColors.kRedColor,
    surface: AppColors.kPrimaryColorDarkMode,
    onSurface: AppColors.kWhiteColor,
    surfaceVariant: AppColors.kSecondColorDarkMode,
    outline: AppColors.kGreyColor,
    background: AppColors.kPrimaryColorDarkMode,
    onBackground: AppColors.kWhiteColor,
    shadow: Colors.black.withOpacity(0.5),
    inverseSurface: AppColors.kWhiteColor,
    onInverseSurface: AppColors.kBlackColor,
    inversePrimary: AppColors.kPrimaryColor,
    surfaceTint: AppColors.kPrimaryColor,
    scrim: Colors.black.withOpacity(0.5),
  ),
  scaffoldBackgroundColor: AppColors.kPrimaryColorDarkMode,
  cardColor: AppColors.kSecondColorDarkMode,
  dialogBackgroundColor: AppColors.kPrimaryColorDarkMode,
  iconTheme: IconThemeData(color: AppColors.kWhiteColor),
  textTheme: const TextTheme(
    titleLarge: TextStyle(
      fontSize: 25,
      fontWeight: FontWeight.w700,
      fontFamily: "Cairo-Bold",
      color: Colors.white,
    ),
    bodyMedium: TextStyle(
      fontSize: 15,
      fontWeight: FontWeight.w400,
      fontFamily: "Cairo-Bold",
      color: Colors.white,
    ),
    bodySmall: TextStyle(fontSize: 15, color: Colors.grey),
  ),
  switchTheme: const SwitchThemeData(
    thumbColor: MaterialStatePropertyAll(Colors.white),
  ),
);
